// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _2doParcial.DAL;

namespace _2doParcial.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20200317165321_Inicial")]
    partial class Inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2");

            modelBuilder.Entity("_2doParcial.Entidades.Llamadas", b =>
                {
                    b.Property<int>("LlamadaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .HasColumnType("TEXT");

                    b.HasKey("LlamadaId");

                    b.ToTable("Llamadas");

                    b.HasData(
                        new
                        {
                            LlamadaId = 1,
                            Descripcion = "Saliente"
                        },
                        new
                        {
                            LlamadaId = 2,
                            Descripcion = "Entrante"
                        });
                });

            modelBuilder.Entity("_2doParcial.Entidades.LlamadasDetalle", b =>
                {
                    b.Property<int>("id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Problema")
                        .HasColumnType("TEXT");

                    b.Property<string>("Solucion")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("LlamadasDetalle");
                });

            modelBuilder.Entity("_2doParcial.Entidades.LlamadasDetalle", b =>
                {
                    b.HasOne("_2doParcial.Entidades.Llamadas", null)
                        .WithMany("Detalles")
                        .HasForeignKey("id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
